version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"    # RABBIT AMQP(Advanced Message Queuing Protocol) PORT
      - "15672:15672"  # MANAGE PORT
    environment:
      - RABBITMQ_DEFAULT_USER=admin  # 기본사용자 이름
      - RABBITMQ_DEFAULT_PASS=1111   # 기본사용자 비밀번호